### ISSUE TITLE
Hosted: Youtube videos have incorrect author

### ISSUE THREAD

**Issue by Rab-C** [karakeep-app/karakeep#2205]
### Describe the Bug

I'm on the hosted version at cloud.karakeep.app. Any Youtube video saved as a bookmark has the first commenter listed as the video author in Karakeep. I previously seen this behaviour in Readeck, if that helps: https://codeberg.org/readeck/readeck/issues/954 

### Steps to Reproduce

Any bookmark that saves a Youtube video, 
whether from RSS feed or manually created,
when viewed in detail view
Has the 'author' in the details panel on the right
Incorrectly substituted for the username of the first commenter

### Expected Behaviour

This was actually a problem I noticed before today, so existed in the previous version as well.

### Exact Karakeep Version

vnightly

### Have you checked the troubleshooting guide?

- [x] I have checked the troubleshooting guide and I haven't found a solution to my problem

**Comment by MohamedBassem** [comment]
This is now fixed (and pushed to the hosted site) by https://github.com/karakeep-app/karakeep/commit/e3cc54636349361a8672dc261973b19680f614e3.

**Comment by Rab-C** [comment]
I am still occasionally seeing this problem on bookmarks of RSS-sourced YT videos, unfortunately. Here are a couple of examples from the last few days.

<img width="1329" height="176" alt="Image" src="https://github.com/user-attachments/assets/b39fb58e-3178-4dfe-a194-d8740bf15fa5" />
<img width="1615" height="328" alt="Image" src="https://github.com/user-attachments/assets/b914aa7f-0e86-4719-9c16-3bf385d50345" />

**Comment by MohamedBassem** [comment]
@Rab-C can you share some of the video links for me to try?

**Comment by Rab-C** [comment]
Sorry about the delay - in the middle of nowhere for Christmas :)

Recent examples, first 2 are the above examples re-verified by bookmarking again - same mis-attribution problem. Though interestingly the second link was attributed to a different (but still incorrect) author from the first time it was bookmarked (see above screenshot vs below). Other 2 are new examples, one from feed, one from manual bookmark.

https://www.youtube.com/watch?v=ThSLfcZfS8A
https://www.youtube.com/watch?v=H_yDqZWhsmM
https://www.youtube.com/watch?v=WKte4ozFPqk
https://www.youtube.com/watch?v=T5s2sNj7Nmc

<img width="1329" height="176" alt="Image" src="https://github.com/user-attachments/assets/f17dd6dc-f29c-473e-bb4f-02ae7819fb5c" />

<img width="1739" height="254" alt="Image" src="https://github.com/user-attachments/assets/946b664d-d279-4360-b6ee-cac7be1d318a" />

<img width="1408" height="211" alt="Image" src="https://github.com/user-attachments/assets/26851358-5d32-4f70-92e3-dfcf5ba39ae0" />

<img width="1746" height="226" alt="Image" src="https://github.com/user-attachments/assets/301238a3-ba2c-4d7e-b944-04f6e9f40c35" />

**Comment by Rab-C** [comment]
Fascinating. I deleted the first link's bookmark. And recreated it a couple of times. And it was finally (on the 3rd or 4th bookmarking) attributed correctly.

<img width="1694" height="192" alt="Image" src="https://github.com/user-attachments/assets/763734ab-af40-4480-869c-41ff1403b2a9" />

Others still incorrect, as of posting.

**Comment by derekgzn** [comment]
Reminder:  AI assisted update on this issue which is still outstanding

Still happening (Aug 2026). Want to add a distinct trigger I hit, different from the original "first commenter" report:

If you save a YouTube video while you're viewing a different channel's page (e.g. you're on Luke's Dev Lab and bookmark a Bijan Bowen video via pasted URL), Karakeep writes the browsing channel as the bookmark's author instead of the video's actual uploader. I confirmed it directly in the DB — bookmarkLinks.author ends up as the wrong channel. The real uploader is trivially correct via YouTube's oEmbed author_name (or yt-dlp). Same broken metadata-extraction class as the thumbnail bug #2204, which was fixed, so this one likely shares a root cause. Would be good to get author extraction fixed upstream too. As a stopgap I overwrite bookmarkLinks.author from oEmbed on crawl — works, but obviously the real fix belongs in the crawler.

Thanks for reviewing.

Derek

**Comment by justadityaraj** [comment]
I'm looking into this. I'll keep the change focused on YouTube author extraction and add a regression test before opening a PR.
